/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ZooGovImport } from './routes/zoo-gov'
import { Route as ZooDeelImport } from './routes/zoo-deel'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ZooGovRoute = ZooGovImport.update({
  id: '/zoo-gov',
  path: '/zoo-gov',
  getParentRoute: () => rootRoute,
} as any)

const ZooDeelRoute = ZooDeelImport.update({
  id: '/zoo-deel',
  path: '/zoo-deel',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/zoo-deel': {
      id: '/zoo-deel'
      path: '/zoo-deel'
      fullPath: '/zoo-deel'
      preLoaderRoute: typeof ZooDeelImport
      parentRoute: typeof rootRoute
    }
    '/zoo-gov': {
      id: '/zoo-gov'
      path: '/zoo-gov'
      fullPath: '/zoo-gov'
      preLoaderRoute: typeof ZooGovImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/zoo-deel': typeof ZooDeelRoute
  '/zoo-gov': typeof ZooGovRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/zoo-deel': typeof ZooDeelRoute
  '/zoo-gov': typeof ZooGovRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/zoo-deel': typeof ZooDeelRoute
  '/zoo-gov': typeof ZooGovRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/zoo-deel' | '/zoo-gov'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/zoo-deel' | '/zoo-gov'
  id: '__root__' | '/' | '/zoo-deel' | '/zoo-gov'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ZooDeelRoute: typeof ZooDeelRoute
  ZooGovRoute: typeof ZooGovRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ZooDeelRoute: ZooDeelRoute,
  ZooGovRoute: ZooGovRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/zoo-deel",
        "/zoo-gov"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/zoo-deel": {
      "filePath": "zoo-deel.tsx"
    },
    "/zoo-gov": {
      "filePath": "zoo-gov.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
