# Development configuration for user "alice"
# Example of how to have separate database instances via config

[database]
path = "pod2-alice.db"

[features]
networking = true
frogcrypto = true

[network]
server = "http://localhost:3000"

[logging]
level = "debug"