# Development configuration for user "bob"
# Example of how to have separate database instances via config

[database]
path = "pod2-bob.db"

[features]
networking = true
frogcrypto = true

[network]
document_server = "http://localhost:3001"  # Different port for separate server
identity_server = "http://localhost:3001"
frogcrypto_server = "http://localhost:3002"

[logging]
level = "debug"