# Local development configuration
# Enables development-friendly features and settings

[features]
networking = true
frogcrypto = true

[network]
document_server = "http://localhost:3000"
identity_server = "http://localhost:3000"
frogcrypto_server = "http://localhost:3001"

[logging]
level = "debug"
console_output = true