# Staging environment configuration

[features]
networking = true
frogcrypto = false

[database]
path = "pod2-staging.db"

[network]
server = "https://staging.pod2.dev"
timeout_seconds = 45

[logging]
level = "info"
console_output = true