# Staging environment configuration

[features]
networking = true
frogcrypto = false

[database]
path = "pod2-staging.db"

[network]
document_server = "https://staging.pod2.dev"
identity_server = "https://staging.pod2.dev"
frogcrypto_server = "https://frog-server-q36c.onrender.com"
timeout_seconds = 45

[logging]
level = "info"
console_output = true