name: Clippy Check

on:
  pull_request:
    branches: [main]
    types: [ready_for_review, opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  clippy:
    if: github.event.pull_request.draft == false
    name: Clippy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2025-01-20
          components: clippy
      - name: Check formatting
        run: cargo clippy
