name: JS Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  merge_group:

jobs:
  test:
    #env:
    #TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    #TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    runs-on:
      labels: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.8.1
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - run: "pnpm install --frozen-lockfile"
      - name: Caching for Turborepo
        uses: rharkor/caching-for-turbo@v1.5
      - run: "pnpm build"
      - run: "pnpm lint"
      - run: "pnpm format:check"
      - run: "pnpm test"
